// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DatabaseContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240820164110_MessageSeed")]
    partial class MessageSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MessageSend")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ModifiedData")
                        .HasColumnType("date");

                    b.Property<bool>("RecipientDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SenderDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "test-1",
                            IsActive = true,
                            MessageSend = new DateTime(2024, 8, 20, 16, 41, 8, 878, DateTimeKind.Utc).AddTicks(3875),
                            ModifiedData = new DateOnly(1, 1, 1),
                            RecipientDeleted = false,
                            RecipientId = 1,
                            RecipientUserName = "Ali",
                            SenderDeleted = false,
                            SenderId = 1,
                            SenderUserName = "Muhammed"
                        },
                        new
                        {
                            Id = 2,
                            Content = "test-2",
                            IsActive = true,
                            MessageSend = new DateTime(2024, 8, 20, 16, 41, 8, 878, DateTimeKind.Utc).AddTicks(3902),
                            ModifiedData = new DateOnly(1, 1, 1),
                            RecipientDeleted = false,
                            RecipientId = 2,
                            RecipientUserName = "Ali",
                            SenderDeleted = false,
                            SenderId = 2,
                            SenderUserName = "Abdo"
                        },
                        new
                        {
                            Id = 3,
                            Content = "test-3",
                            IsActive = true,
                            MessageSend = new DateTime(2024, 8, 20, 16, 41, 8, 878, DateTimeKind.Utc).AddTicks(3905),
                            ModifiedData = new DateOnly(1, 1, 1),
                            RecipientDeleted = false,
                            RecipientId = 3,
                            RecipientUserName = "Abdo",
                            SenderDeleted = false,
                            SenderId = 3,
                            SenderUserName = "Muhammed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
